[project]
name = "app-of-apps"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.1.0",
    "django>=5.1.6",
    "django-extensions>=3.2.3",
    "pytest>=8.3.4",
    "pytest-django>=4.10.0",
]
