# Generated by Django 5.1.6 on 2025-02-18 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Permission",
            new_name="AppPermission",
        ),
    ]
