# Generated by Django 5.1.6 on 2025-02-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applications",
            name="deleted_ts",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="applications",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
