# Generated by Django 5.1.6 on 2025-02-12 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0002_alter_applications_deleted_ts_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Applications",
            new_name="Application",
        ),
    ]
